apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature

spec:
  validationFailureAction: Enforce
  rules:
  - name: check-image-signature
    match:
      resources:
        kinds:
        - Pod

    verifyImages:
    - image: "docker.io/shadab256/*"
      key: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0p6Sy0jJm+HPBk87GpGK/VvVGDfg
        r05VIGONNq6BzLg5b83c/ZwbBzx66Tp4m9cVB4m+GSxY0Axh6LPhnQU/ZA==
        -----END PUBLIC KEY-----