apiVersion: v1
kind: ServiceAccount
Metadata:
  name: app-sa
  namespace: production

apiVersion: rbac.authorization.k8s.io/v1
kind: Role  
Metadata:
  name: app-role 
  namespace: production

Rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding 
  namespace: production

subjects:
- kind: ServiceAccount
  name: app-sa

roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io