apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: default
  labels: 
    app: secure-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: secure-app

  template:
    metadata:
      labels:
        app: secure-app

    spec:
      serviceAccountName: app-sa

      containers:
      - name: secure-app
        image: docker.io/shadab256/secure-app:7fd4f319558e85ca7b18222dff29378f601db5f3
        ports:
        - containerPort: 5000

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false

          